### ISSUE TITLE
Error: Inconsistent tensor size

### ISSUE THREAD

**Issue by saumitrasharma** [senisioi/NeuralTextSimplification#1]
![image](https://user-images.githubusercontent.com/29398060/27118246-0e94d7da-50f8-11e7-8a76-dd883ecbf270.png)

While running translate.sh, I am getting the following error: 
/home/ubuntu/torch/install/bin/luajit: /home/ubuntu/torch/install/share/lua/5.1/nn/JoinTable.lua:39: inconsistent tensor size at /home/ubuntu/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:17

Attached is a screenshot for your reference. Any idea why this is happening?

**Comment by senisioi** [comment]
Yes, it looks like it's not compatible with the latest version of torch. For now, the only solution I can provide is to go into your torch checkout and pull this change:
```bash
git checkout  d03a42834bb1b674495b0c42de1716b66cc388f1
```
then install
```bash
./install.sh
```
