### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by bwindsor22** [senisioi/NeuralTextSimplification#5]
Hi Sergiu, would you mind indicating what license this code is under? E.g. is it open source (like MIT, Apache...)

**Comment by senisioi** [comment]
Hi Brad, the [OpenNMT part](https://github.com/OpenNMT/OpenNMT/blob/master/LICENSE.md) is MIT license and the rest is use-however-you-like

**Comment by bwindsor22** [comment]
Wonderful, thank you so much Sergiu!  Closing the issue.
