### ISSUE TITLE
Running Problem for the third command

### ISSUE THREAD

**Issue by CarolLi** [senisioi/NeuralTextSimplification#6]
Can anyone tell me why the process of the third command stopped at this stage?
`(py3) Apples-iMac:NeuralTextSimplification apple$ python src/download_models.py ./models
[LINE:53]# INFO     [2019-01-22 15:06:32,095]  Saving files to: ./models
[LINE:10]# INFO     [2019-01-22 15:06:32,096]  Downloading 0B_pjS_ZjPfT9dEtrbV85UXhSelU to ./models/NTS_epoch11_10.19.t7
[LINE:11]# INFO     [2019-01-22 15:06:32,096]  Please be patient, it may take a while...
[LINE:824]# DEBUG    [2019-01-22 15:06:32,222]  Starting new HTTPS connection (1): docs.google.com
[LINE:396]# DEBUG    [2019-01-22 15:06:32,599]  https://docs.google.com:443 "GET /uc?export=download&id=0B_pjS_ZjPfT9dEtrbV85UXhSelU HTTP/1.1" 200 None
[LINE:16]# INFO     [2019-01-22 15:06:32,600]  ...
[LINE:824]# DEBUG    [2019-01-22 15:06:32,602]  Starting new HTTPS connection (2): docs.google.com
[LINE:396]# DEBUG    [2019-01-22 15:06:32,891]  https://docs.google.com:443 "GET /uc?export=download&confirm=5MMl&id=0B_pjS_ZjPfT9dEtrbV85UXhSelU HTTP/1.1" 302 None
[LINE:824]# DEBUG    [2019-01-22 15:06:32,894]  Starting new HTTPS connection (1): doc-0o-1g-docs.googleusercontent.com
[LINE:396]# DEBUG    [2019-01-22 15:06:35,749]  https://doc-0o-1g-docs.googleusercontent.com:443 "GET /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/q8872a9n7poj4sqt0mouh1jdqbo4ou8h/1548136800000/06297222380386734599/*/0B_pjS_ZjPfT9dEtrbV85UXhSelU?e=download HTTP/1.1" 200 None`

**Comment by senisioi** [comment]
The code contained a trick to download files from google drive. I think the trick doesn't work anymore with the google api.
Maybe the safest thing to do is to download the models from using the browser:
    - for NTS:
        https://drive.google.com/open?id=0B_pjS_ZjPfT9dEtrbV85UXhSelU
    -for NTS-w2v:
        https://drive.google.com/open?id=0B_pjS_ZjPfT9ZTRfSFp4Ql92U0E
