### ISSUE TITLE
Unable to run translate.sh successfully

### ISSUE THREAD

**Issue by VishweshS** [senisioi/NeuralTextSimplification#8]
Getting this error: ./translate.sh: line 18: 28642 Segmentation fault

**Comment by senisioi** [comment]
I am sorry to hear that. What I observed myself is that the continuous changes in third party libraries makes it really difficult to reproduce the results in the paper. Please share the torch and OpenNMT versions that you have installed.

**Comment by VishweshS** [comment]
I installed the pre-trained models using the src/download_models.py file.
I am using Torch7 version.
I am just trying to follow the instructions given under the heading "Simplify Text | Generate Predictions (no GPUs needed)".
But, when I run the file "translate.sh", I am getting a segmentation fault.
